builders:
#  property_multiply:
#    import: "package:flutter_useful_things/database/build.dart"
#    builder_factories: ["teste"]
#    build_extensions: {".dart": ["multiply.g.part"]}
#    auto_apply: dependents
#    build_to: cache
#    applies_builders: ["source_gen|combining_builder"]

  json_generator:
    import: "package:flutter_useful_things/json/build.dart"
    builder_factories: ["jsonGenerator"]
    build_extensions: {".dart": ["json.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]