name: flutter_useful_things
description: A infrastructure lib

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^0.1.3
  rxdart: 0.27.0
  carousel_slider: 2.0.0
  flutter_credit_card: 0.1.1
  cached_network_image: 3.0.0
  connectivity: '>=0.4.8+5 <2.0.0'
  source_gen: 1.0.0
  dio: 4.0.0
  build: 2.0.1
  analyzer: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
